version: "3.4"
services:

  app:
    container_name: firepoker-dev

    image: firepoker-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev

    volumes:
      - .:/src
    ports:
      - 8000:9000
      - 35729:35729
  nginx:
    image: "nginx:alpine"
    ports:
      - 5043:443
    links:
      - app:app
    volumes:
      - ./auth:/etc/nginx/conf.d
      - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro